### ISSUE TITLE
Make textures have more detail

### ISSUE THREAD

**Issue by Tim79000** [EmptyStar/asuna#52]
Dirt is very cartoony, and wood isn't contrasting enough, thus making me not like this game for building.

**Comment by Tim79000** [comment]
Please.

**Comment by EmptyStar** [comment]
There is already an open issue for replacing textures, #52, which will likely see some progress in the next release or the release after. I agree that the original dirt texture was not great and it was removed in the last release; make sure you're using the latest `beta-12` release.

In the meantime, consider using a texture pack for the textures you don't like. I'm personally a huge fan of [defaultpack Remastered](https://content.minetest.net/packages/tinneh/defaultpack_remastered/) which adds great look to the default Minetest Game nodes. [PixelBOX](https://content.minetest.net/packages/jp/pixelbox/) is another great choice. You'll find these and plenty of other texture packs on ContentDB.

I'm going to close this issue as a duplicate of #52 and also because the cartoony dirt texture has already been removed in the latest release.
