### ISSUE TITLE
Terracota desert ground is flammable

### ISSUE THREAD

**Issue by sem-geologist** [EmptyStar/asuna#53]
I would like to know if that is intended behavior. In one of my maps while looking around `fiery` biome I came across `teracotta` (with cactuses) biome. Which suddenly catched the fire from nearby lava of fiery biome, and fire was spreading like crazy burning the ground (ironically not setting cactuses on fire). I checked the code and see that teraccota clays for that biome are set `flammable=2`  so it is highly flammable. It is scary, buggy (leaves the floating cactuses in the air after burning off teracotta clay blocks) and in same time wondering as that gives kind of hellish landscape.

**Comment by EmptyStar** [comment]
I would certainly prefer it to not be flammable. It's a simple enough fix to remove the `flammable` group, but it's mostly a moot point because I'm replacing the terracotta biome with the forsaken desert biome from [Everness](https://content.minetest.net/packages/SaKeL/everness/) in the next release of Asuna. The terracotta nodes will still exist and and I'll remove the group for the sake of correctness, but in the future, these nodes will only be accessible via creative inventory.

Thanks anyways for catching this, I'll add this issue to the milestone for the next release.

**Comment by EmptyStar** [comment]
Boom, easy fix. Thanks again. 🙂
