### ISSUE TITLE
Sprinting does not work

### ISSUE THREAD

**Issue by fgaz** [EmptyStar/asuna#57]
From the readme:

> Players will enjoy the following effects when they have eaten:
> * The ability to sprint (+100% movement speed while holding the `aux1` key)

But when I press Aux1 at full nutrition nothing happens

**Comment by EmptyStar** [comment]
Are you holding the key down or are you just pressing it? You do have to hold the key down to sprint.

The other likely cause is that you have fast privilege granted. Sprinting is suppressed for players with fast privilege because it's way faster than sprinting and works exactly the same way when toggled on (`j` key by default).

I could enable sprinting with fast privilege which would make sprinting **LUDICROUS SPEED**, and it might be less confusing and more consistent to do that anyways. And it would be slightly better performing since it wouldn't need to check fast privilege on every movement tick.

Let me think about it for a bit, and I'm open to feedback. In the meantime, if you suspect fast privilege might be the issue, try the command `/revokeme fast` to see if sprinting works without fast privilege (and `/grantme fast` to get it back).

**Comment by fgaz** [comment]
It was the fast privilege, thanks!

I think it should be possible to sprint even when `fast` is granted. When hosting a server I usually `/grantme all` just in case I need the privs for administrative tasks, then play normally. In that case resorting to `j` for sprinting would be cheating, as it's way faster and requires flying.

If you decide to keep it like this, I think it should be noted in the readme to avoid confusion

**Comment by EmptyStar** [comment]
I think allowing sprint with fast privilege is the way to go. Anyone using fast privilege knows what they're doing and any interactions with sprint should be expected. I'll adjust it shortly and I'll keep this issue open to track the change.

**Comment by EmptyStar** [comment]
:running_woman::dash:
